### ISSUE TITLE
기존에 있는것들 이전

### ISSUE THREAD

**Issue by seapy** [rorlakr/rubyworld#1]
https://github.com/rorlakr/rorla_api/wiki/%EA%B0%9C%EB%B0%9C%EC%97%90-%EB%8F%84%EC%9B%80%EC%9D%B4-%EB%90%98%EB%8A%94-%EC%9E%90%EB%A3%8C-%EB%AA%A8%EC%9D%8C#레일스를-활용한-사이트

**Comment by wagurano** [comment]
### 오프라인 모임에서 나온 이름:
1. 루비월드 rubyworld

### 슬랙에서 나온 저장소 이름:
1. 오썸 루비, 레일스 코리아
2. 오쏘오세요. 루비
3. 루비야 놀자
4. 모여라 루비스트
5. 코리안 루비스트
6. 루비와 친구들 또는 friends with ruby
7. Land of ruby 루비 나라
8. rubyguys
9. koruby

**Comment by seapy** [comment]
기존에 정리하셨던 몇개 사이트는 더이상 레일스가 아닌것으로 보여서 제외했습니다.
- 쿠폰모아, 포켓스타일
